### ISSUE TITLE
Autocomplete loses focus when deleting an entry.

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [blackbaud/skyux-lookup#49] opened 2019-12-10 19:44 UTC
### Expected behavior

1. `sky-autocomplete` is pre-loaded with data on component initialization.

2. I highlight the text and hit "Backspace"

3. I'd expect the input to stay focused on until the user clicks out of it.

### Actual behavior

Focus is lost after step 2. It seems to wait the amount of time specified in `debounceTime` before losing focus.

### Steps to reproduce

1. `sky-autocomplete` is pre-loaded with data on component initialization.

2. Highlight the text and hit "Backspace"

3. See focus is lost.

### Severity

Medium?  I imagine consumers will get annoyed with losing focus.

### Impact

Medium.
[Video](https://blackbaud.slack.com/files/U1EDQD3SR/FRH908VLL/blackbaud_-_google_chrome_2019-12-10_14-25-17.mp4)

**Comment by Blackbaud-TrevorBurch** [comment] 2020-03-13 19:26
@blackbaud-joshlandi I was not able to reproduce this today with either a template or reactive driven form. I think it might have been fixed in the three months since this was filed. If you are still seeing this behavior please let me know and we can reopen

**Closed by Blackbaud-TrevorBurch** 2020-03-13 19:26 UTC
Labels: From: Consumer, Impact: High, Severity: Medium, Type: Bug
